const state={rows:[],files:[]};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const aliases={item:['item','item_name','الصنف','اسم الصنف','الوصف','الصنف/الوصف','البندر'],branch:['branch','الفرع','اسم الفرع','الفرع المستفيد'],qty:['qty','quantity','الكمية','كمية','عدد'],amount:['amount','cost','total','المبلغ','التكلفة','التكلفة ٢','الإجمالي','اجمالي','القيمة'],percent:['percent','percentage','النسبة']};
const months={يناير:'01',يناير:'01',فبراير:'02',مارس:'03',أبريل:'04',ابريل:'04',مايو:'05',يونيو:'06',يوليو:'07',أغسطس:'08',اغسطس:'08',أغست:'08',سبتمبر:'09',أكتوبر:'10',اكتوبر:'10',نوفمبر:'11',ديسمبر:'12',ديسمبـر:'12',jan:'01',january:'01',feb:'02',february:'02',mar:'03',march:'03',apr:'04',april:'04',may:'05',jun:'06',june:'06',jul:'07',july:'07',aug:'08',august:'08',sep:'09',september:'09',oct:'10',october:'10',nov:'11',november:'11',dec:'12',december:'12'};
function normalize(s=''){return String(s).trim().toLowerCase().replace(/[ًٌٍَُِّْـ]/g,'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}]+/gu,' ')}
function latinDigits(s){return String(s).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d))}
function parsePeriod(name){const n=latinDigits(name).toLowerCase(); let m=n.match(/(20\d{2})[\s_-]*(0?[1-9]|1[0-2])/); if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}`; let y=n.match(/(20\d{2})/); for(const [key,val] of Object.entries(months)){if(n.includes(key))return `${y?.[1]||new Date().getFullYear()}-${val}`} return ''}
function number(v){if(v==null||v==='')return 0; let s=latinDigits(String(v)).replace(/[٬,،]/g,'').replace(/[٫]/g,'.').replace(/[^\d.-]/g,''); return Number(s)||0}
function findCol(headers,kind){const clean=headers.map(h=>normalize(h)); for(const a of aliases[kind]){const i=clean.findIndex(h=>h===normalize(a)||h.includes(normalize(a))); if(i>=0)return headers[i]} return null}
function mapRows(records,fileName){if(!records.length)return []; const headers=Object.keys(records[0]); const cols={item:findCol(headers,'item'),branch:findCol(headers,'branch'),qty:findCol(headers,'qty'),amount:findCol(headers,'amount')}; const period=parsePeriod(fileName); return records.map((r,i)=>({item:String(r[cols.item]??'غير محدد').trim()||'غير محدد',branch:String(r[cols.branch]??'غير محدد').trim()||'غير محدد',qty:number(r[cols.qty]),amount:number(r[cols.amount]),period:period||'غير محدد',raw:i+1})).filter(r=>r.item!=='غير محدد'||r.branch!=='غير محدد')}
function parseCsv(text){const lines=text.split(/\r?\n/).filter(Boolean); const sep=lines[0]?.includes(';')?';':','; const parse=l=>l.split(sep).map(x=>x.trim().replace(/^['"]|['"]$/g,'')); const headers=parse(lines[0]); return lines.slice(1).map(l=>Object.fromEntries(parse(l).map((v,i)=>[headers[i]||`col${i}`,v])))}
async function readFile(file){if(file.name.toLowerCase().endsWith('.csv'))return parseCsv(await file.text()); const data=await file.arrayBuffer(); const wb=XLSX.read(data,{type:'array'}); const sheet=wb.Sheets[wb.SheetNames[0]]; return XLSX.utils.sheet_to_json(sheet,{defval:''})}
function fmt(n){return new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(n)}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function update(){const rows=state.rows; const totalA=rows.reduce((s,r)=>s+r.amount,0),totalQ=rows.reduce((s,r)=>s+r.qty,0); $('#totalAmount').textContent=fmt(totalA);$('#totalQty').textContent=fmt(totalQ);$('#itemCount').textContent=fmt(new Set(rows.map(r=>r.item)).size);$('#branchCount').textContent=fmt(new Set(rows.map(r=>r.branch)).size);$('#amountTrend').textContent=rows.length?'من البيانات المرفوعة':'بانتظار البيانات';$('#qtyTrend').textContent=rows.length?'من البيانات المرفوعة':'بانتظار البيانات';$('#rowCount').textContent=`${fmt(rows.length)} صف منظف`; $('#emptyState').classList.toggle('hidden',rows.length>0);$('#dataState').classList.toggle('hidden',!rows.length); renderCharts();renderTable();renderInsights();}
function renderCharts(){const rows=state.rows; const byItem={};rows.forEach(r=>byItem[r.item]=(byItem[r.item]||0)+r.amount); const items=Object.entries(byItem).sort((a,b)=>b[1]-a[1]).slice(0,8);const max=items[0]?.[1]||1;$('#barChart').innerHTML=items.map(([n,v])=>`<div class="bar-row"><span class="bar-label" title="${n}">${n}</span><div class="bar-track"><i class="bar-fill" style="width:${v/max*100}%"></i></div><span class="bar-value">${fmt(v)}</span></div>`).join('')||'<p class="muted">لا توجد مبالغ قابلة للرسم.</p>'; const byBranch={};rows.forEach(r=>byBranch[r.branch]=(byBranch[r.branch]||0)+r.amount);const branches=Object.entries(byBranch).sort((a,b)=>b[1]-a[1]);const total=branches.reduce((s,x)=>s+x[1],0)||1;$('#branchChart').innerHTML=branches.map(([n,v])=>`<div class="branch-row"><span class="branch-dot"></span><span class="branch-name">${n}</span><span class="branch-meter"><i style="width:${v/total*100}%"></i></span><span class="branch-pct">${Math.round(v/total*100)}%</span></div>`).join('')||'<p class="muted">لا توجد فروع.</p>'; const select=$('#branchFilter');const val=select.value;select.innerHTML='<option value="">كل الفروع</option>'+Object.keys(byBranch).sort().map(b=>`<option>${b}</option>`).join('');select.value=val}
function renderTable(){const branch=$('#branchFilter').value, query=normalize($('#itemFilter').value);const rows=state.rows.filter(r=>(!branch||r.branch===branch)&&(!query||normalize(r.item).includes(query))).slice(0,100);$('#dataTable').innerHTML=rows.map(r=>`<tr><td>${r.item}</td><td>${r.branch}</td><td>${fmt(r.qty)}</td><td>${fmt(r.amount)}</td><td>${r.period}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">لا توجد نتائج.</td></tr>'}
function renderInsights(){const rows=state.rows;if(!rows.length)return;const total=rows.reduce((s,r)=>s+r.amount,0),byItem={};rows.forEach(r=>byItem[r.item]=(byItem[r.item]||0)+r.amount);const top=Object.entries(byItem).sort((a,b)=>b[1]-a[1])[0];const byBranch={};rows.forEach(r=>byBranch[r.branch]=(byBranch[r.branch]||0)+r.amount);const branch=Object.entries(byBranch).sort((a,b)=>b[1]-a[1])[0];const insights=[];if(top)insights.push({title:'الصنف الأعلى مساهمة',text:`${top[0]} يمثل ${Math.round(top[1]/(total||1)*100)}% من إجمالي المبلغ بقيمة ${fmt(top[1])}. راجع سبب التركّز قبل اتخاذ قرار شراء أو توزيع.`,level:''});if(branch)insights.push({title:'الفرع الأعلى قيمة',text:`${branch[0]} يتصدر الفروع بمبلغ ${fmt(branch[1])}. قارن الكمية والمبلغ مع الفروع الأخرى لتحديد ما إذا كان الفرق ناتجًا عن الحجم أو التكلفة.`,level:'medium'});if(rows.some(r=>r.period==='غير محدد'))insights.push({title:'تنبيه جودة البيانات',text:'بعض الملفات لم تحمل شهرًا واضحًا من الاسم. أعد تسمية الملف بصيغة مثل «سوالب اغسطس ٢٠٢٦.xlsx» للحصول على مقارنة زمنية أدق.',level:'medium'});$('#insightsList').innerHTML=insights.map(i=>`<article class="insight ${i.level}"><h3>${i.title}</h3><p>${i.text}</p></article>`).join('')}
async function ingest(files){for(const file of files){if(!/\.(csv|xlsx|xls)$/i.test(file.name)){showToast(`الملف ${file.name} غير مدعوم`);continue}try{const records=await readFile(file);const rows=mapRows(records,file.name);state.rows.push(...rows);state.files.push({name:file.name,count:rows.length,period:parsePeriod(file.name)});$('#fileList').insertAdjacentHTML('beforeend',`<div class="file-row"><div><b>${file.name}</b><br><span>${fmt(rows.length)} صف · ${parsePeriod(file.name)||'الشهر غير محدد'}</span></div><span>✓ تم التحليل</span></div>`)}catch(e){showToast(`تعذر قراءة ${file.name}`)}}update();if(state.rows.length){showToast('تمت معالجة الملفات محليًا بنجاح');navigate('dashboard')}}
function navigate(view){$$('.view').forEach(v=>v.classList.remove('active-view'));$(`#view-${view}`).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view))}
$$('.nav-item').forEach(n=>n.addEventListener('click',()=>navigate(n.dataset.view)));$$('.go-upload').forEach(b=>b.addEventListener('click',()=>navigate('upload')));$('#dropzone .primary-btn').addEventListener('click',()=>$('#fileInput').click());$('#fileInput').addEventListener('change',e=>ingest([...e.target.files]));['dragenter','dragover'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();$('#dropzone').classList.add('drag')}));['dragleave','drop'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();$('#dropzone').classList.remove('drag')}));$('#dropzone').addEventListener('drop',e=>ingest([...e.dataTransfer.files]));$('#branchFilter').addEventListener('change',renderTable);$('#itemFilter').addEventListener('input',renderTable);$('#resetBtn').addEventListener('click',()=>{state.rows=[];state.files=[];$('#fileList').innerHTML='';$('#fileInput').value='';update();navigate('dashboard');showToast('تمت إعادة ضبط الجلسة')});
update();
